### ISSUE TITLE
zlmediakit 问题

### ISSUE THREAD

**Issue by fajiao** [xiangxud/webrtc_H265player#2]
1. 使用提供的 zlmediakit 程序可以播放 webrtc h265，但是自己编译的 zlmediakit 程序却不行。
2. 使用提供的 zlmediakit 程序能播放，但视频底部呈条状发绿。

注：自己编译的 zlmediakit 可以用其自带的 webrtc 测试页面播放 h264，连接 h265 能读条但播放不了。第一条问题测试时，通过码流抓包分析，ice连接也都正常，request和answer应答也成功了，但是 datachannel 没打开。 停止播放后，zlmediakit 后台也显示关闭了连接。不知道问题出现在哪里？

**Comment by xiangxud** [comment]
ffmpeg yuv data 16 bit stribe 1080 as 1088
