### ISSUE TITLE
支持ws-flv h264/h265 + G711a吗

### ISSUE THREAD

**Issue by KAN-007** [xiangxud/webrtc_H265player#4]

**Comment by xiangxud** [comment]
不支持，这个项目改至https://github.com/goldvideo/decoder_wasm，它可以支持ws，我去掉了

**Comment by KAN-007** [comment]
音频格式为G711a也可以吗？，https-flv/ws-flv  + h265/h264

**Comment by xiangxud** [comment]
G711a webrtc是支持的 当前 WebRTC 支持 ilbc、isac、G711、G722 和 opus 等，我使用的opus
