### ISSUE TITLE
从metartc拉流播放走的是标准的webrtc收流吗，srtp音视频数据吗，如果需要去掉srtp,能支持吗

### ISSUE THREAD

**Issue by feigegithub** [xiangxud/webrtc_H265player#6]
从metartc拉流播放走的是标准的webrtc收流吗，是srtp音视频数据吗，如果需要去掉srtp,只走rtp,能支持吗

**Comment by xiangxud** [comment]
数据走的标准webrtc datachannel通道，浏览器是否支持不太清楚，没有实际过你说的，但在通道上传rtp是没有问题的，据我了解，目前只有safari支持直接用rtp通道来传，能否免密需要看看相关api

**Comment by feigegithub** [comment]
> 数据走的标准webrtc datachannel通道，浏览器是否支持不太清楚，没有实际过你说的，但在通道上传rtp是没有问题的，据我了解，目前只有safari支持直接用rtp通道来传，能否免密需要看看相关api

如果是走标准的webrtc datachanel通道，应该就是用的dtls加密的。在通用浏览器比如chrome/firefox浏览器有没有什么办法去掉webrtc的srtp加密也能推送到网页端去播放，毕竟这个srtp加密对端来说比较耗CPU。
