### ISSUE TITLE
zlm的mediaserver搭建好之后，怎么用这个 webrtc_H265player播放器播放

### ISSUE THREAD

**Issue by tigerthu** [xiangxud/webrtc_H265player#7]
我mediaserver搭建好之后，拉流H264代理已成功，可以在zlm自带的webrtc测试界面里播放webrtc的视频了。
webrtc的地址为：http://127.0.0.1/index/api/webrtc?app=live&stream=test&type=play
![image](https://github.com/xiangxud/webrtc_H265player/assets/22852949/819ef144-2183-4380-9142-adf4766e8df0)

但是在您提供的zlm_cptc版本程序中打开index.html后，不知道怎么播放。
![image](https://github.com/xiangxud/webrtc_H265player/assets/22852949/2c2d2a56-f863-4178-8af4-3dcdf801dcba)

能否麻烦指点下：播放地址应该是什么，怎么播放。

**Comment by xiangxud** [comment]
like this pull by need https://192.168.0.133:443/index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=live&stream=stream0&url=rtsp://

**Comment by tigerthu** [comment]
> like this pull by need https://192.168.0.133:443/index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=live&stream=stream0&url=rtsp://

您这个是在zlm里面添加流代理的http api，这一步我操作成功了。也可以用zlm自带的播放器打开这个webrtc的流，用这个地址：http://127.0.0.1/index/api/webrtc?app=live&stream=test&type=play

就是想请教下用您发布的的这个zlm_cptc版本index.html怎么播放zlm里面的这个流，应该用什么地址。

**Comment by xiangxud** [comment]
流的名字一样即可，我给你的地址是按需拉流的
